//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.20 at 11:04:04 AM BST 
//


package org.openehr.schemas.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RESOURCE_DESCRIPTION complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RESOURCE_DESCRIPTION">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="original_author" type="{http://schemas.openehr.org/v1}StringDictionaryItem" maxOccurs="unbounded"/>
 *         &lt;element name="other_contributors" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="lifecycle_state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="resource_package_uri" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="other_details" type="{http://schemas.openehr.org/v1}StringDictionaryItem" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="details" type="{http://schemas.openehr.org/v1}RESOURCE_DESCRIPTION_ITEM" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="parent_resource" type="{http://schemas.openehr.org/v1}AUTHORED_RESOURCE" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RESOURCE_DESCRIPTION", propOrder = {
    "originalAuthor",
    "otherContributors",
    "lifecycleState",
    "resourcePackageUri",
    "otherDetails",
    "details",
    "parentResource"
})
public class RESOURCEDESCRIPTION {

    @XmlElement(name = "original_author", required = true)
    protected List<StringDictionaryItem> originalAuthor;
    @XmlElement(name = "other_contributors")
    protected List<String> otherContributors;
    @XmlElement(name = "lifecycle_state", required = true)
    protected String lifecycleState;
    @XmlElement(name = "resource_package_uri")
    protected String resourcePackageUri;
    @XmlElement(name = "other_details")
    protected List<StringDictionaryItem> otherDetails;
    protected List<RESOURCEDESCRIPTIONITEM> details;
    @XmlElement(name = "parent_resource")
    protected AUTHOREDRESOURCE parentResource;

    /**
     * Gets the value of the originalAuthor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the originalAuthor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOriginalAuthor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StringDictionaryItem }
     * 
     * 
     */
    public List<StringDictionaryItem> getOriginalAuthor() {
        if (originalAuthor == null) {
            originalAuthor = new ArrayList<StringDictionaryItem>();
        }
        return this.originalAuthor;
    }

    /**
     * Gets the value of the otherContributors property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherContributors property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherContributors().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getOtherContributors() {
        if (otherContributors == null) {
            otherContributors = new ArrayList<String>();
        }
        return this.otherContributors;
    }

    /**
     * Gets the value of the lifecycleState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLifecycleState() {
        return lifecycleState;
    }

    /**
     * Sets the value of the lifecycleState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLifecycleState(String value) {
        this.lifecycleState = value;
    }

    /**
     * Gets the value of the resourcePackageUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourcePackageUri() {
        return resourcePackageUri;
    }

    /**
     * Sets the value of the resourcePackageUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourcePackageUri(String value) {
        this.resourcePackageUri = value;
    }

    /**
     * Gets the value of the otherDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StringDictionaryItem }
     * 
     * 
     */
    public List<StringDictionaryItem> getOtherDetails() {
        if (otherDetails == null) {
            otherDetails = new ArrayList<StringDictionaryItem>();
        }
        return this.otherDetails;
    }

    /**
     * Gets the value of the details property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the details property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RESOURCEDESCRIPTIONITEM }
     * 
     * 
     */
    public List<RESOURCEDESCRIPTIONITEM> getDetails() {
        if (details == null) {
            details = new ArrayList<RESOURCEDESCRIPTIONITEM>();
        }
        return this.details;
    }

    /**
     * Gets the value of the parentResource property.
     * 
     * @return
     *     possible object is
     *     {@link AUTHOREDRESOURCE }
     *     
     */
    public AUTHOREDRESOURCE getParentResource() {
        return parentResource;
    }

    /**
     * Sets the value of the parentResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link AUTHOREDRESOURCE }
     *     
     */
    public void setParentResource(AUTHOREDRESOURCE value) {
        this.parentResource = value;
    }

}
