/*******************************************************************************
 * Copyright 2012 Sevket Seref Arikan, David Ingram
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from aom.proto

package bosphoruspojos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public final class ArchtypeInternalRef implements Externalizable, Message<ArchtypeInternalRef>
{

    public static Schema<ArchtypeInternalRef> getSchema()
    {
        return SCHEMA;
    }

    public static ArchtypeInternalRef getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final ArchtypeInternalRef DEFAULT_INSTANCE = new ArchtypeInternalRef();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    String path;

    public ArchtypeInternalRef()
    {
        
    }

    public ArchtypeInternalRef(
        String path
    )
    {
        this.path = path;
    }

    // getters and setters

    // path

    public String getPath()
    {
        return path;
    }

    public void setPath(String path)
    {
        this.path = path;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<ArchtypeInternalRef> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<ArchtypeInternalRef> SCHEMA = new Schema<ArchtypeInternalRef>()
    {
        // schema methods

        public ArchtypeInternalRef newMessage()
        {
            return new ArchtypeInternalRef();
        }

        public Class<ArchtypeInternalRef> typeClass()
        {
            return ArchtypeInternalRef.class;
        }

        public String messageName()
        {
            return ArchtypeInternalRef.class.getSimpleName();
        }

        public String messageFullName()
        {
            return ArchtypeInternalRef.class.getName();
        }

        public boolean isInitialized(ArchtypeInternalRef message)
        {
            return 
                message.path != null;
        }

        public void mergeFrom(Input input, ArchtypeInternalRef message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        message.path = input.readString();
                        break;
                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, ArchtypeInternalRef message) throws IOException
        {
            if(message.path == null)
                throw new UninitializedMessageException(message);
            output.writeString(1, message.path, false);
        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "path";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("path", 1);
        }
    };
    
}
