/*******************************************************************************
 * Copyright 2012 Sevket Seref Arikan, David Ingram
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from aom.proto

package bosphoruspojos;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class ArchetypeSlot implements Externalizable, Message<ArchetypeSlot>
{

    public static Schema<ArchetypeSlot> getSchema()
    {
        return SCHEMA;
    }

    public static ArchetypeSlot getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final ArchetypeSlot DEFAULT_INSTANCE = new ArchetypeSlot();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    List<String> includes;
    List<String> excludes;

    public ArchetypeSlot()
    {
        
    }

    // getters and setters

    // includes

    public List<String> getIncludesList()
    {
        return includes;
    }

    public void setIncludesList(List<String> includes)
    {
        this.includes = includes;
    }

    // excludes

    public List<String> getExcludesList()
    {
        return excludes;
    }

    public void setExcludesList(List<String> excludes)
    {
        this.excludes = excludes;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<ArchetypeSlot> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<ArchetypeSlot> SCHEMA = new Schema<ArchetypeSlot>()
    {
        // schema methods

        public ArchetypeSlot newMessage()
        {
            return new ArchetypeSlot();
        }

        public Class<ArchetypeSlot> typeClass()
        {
            return ArchetypeSlot.class;
        }

        public String messageName()
        {
            return ArchetypeSlot.class.getSimpleName();
        }

        public String messageFullName()
        {
            return ArchetypeSlot.class.getName();
        }

        public boolean isInitialized(ArchetypeSlot message)
        {
            return true;
        }

        public void mergeFrom(Input input, ArchetypeSlot message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        if(message.includes == null)
                            message.includes = new ArrayList<String>();
                        message.includes.add(input.readString());
                        break;
                    case 2:
                        if(message.excludes == null)
                            message.excludes = new ArrayList<String>();
                        message.excludes.add(input.readString());
                        break;
                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, ArchetypeSlot message) throws IOException
        {
            if(message.includes != null)
            {
                for(String includes : message.includes)
                {
                    if(includes != null)
                        output.writeString(1, includes, true);
                }
            }

            if(message.excludes != null)
            {
                for(String excludes : message.excludes)
                {
                    if(excludes != null)
                        output.writeString(2, excludes, true);
                }
            }
        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "includes";
                case 2: return "excludes";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("includes", 1);
            fieldMap.put("excludes", 2);
        }
    };
    
}
