/*******************************************************************************
 * Copyright 2012 Sevket Seref Arikan, David Ingram
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
package uk.ac.ucl.chime.gui;



import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.Random;

import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.Box.Filler;

/**
 *
 * @author  __USER__
 */
public class GridBagTest extends javax.swing.JFrame {

//	/** Creates new form GridBagTest */
//	public GridBagTest() {
//		initComponents();
//	}
//
//	/** This method is called from within the constructor to
//	 * initialize the form.
//	 * WARNING: Do NOT modify this code. The content of this method is
//	 * always regenerated by the Form Editor.
//	 */
//	//GEN-BEGIN:initComponents
//	// <editor-fold defaultstate="collapsed" desc="Generated Code">
//	private void initComponents() {
//
//		pnlMain = new javax.swing.JPanel();
//
//		setDefaultCloseOperation(3);
//
//		pnlMain.setLayout(new TableLayout(new double[]{400,400}, new double[]{100, 100}));
//		pnlMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
//
//		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
//				getContentPane());
//		getContentPane().setLayout(layout);
//		layout.setHorizontalGroup(layout.createParallelGroup(
//				org.jdesktop.layout.GroupLayout.LEADING).add(
//				layout.createSequentialGroup().addContainerGap().add(pnlMain,
//						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 376,
//						Short.MAX_VALUE).addContainerGap()));
//		layout.setVerticalGroup(layout.createParallelGroup(
//				org.jdesktop.layout.GroupLayout.LEADING).add(
//				layout.createSequentialGroup().addContainerGap().add(pnlMain,
//						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 276,
//						Short.MAX_VALUE).addContainerGap()));
//
//		pack();
//	}// </editor-fold>
//	//GEN-END:initComponents
//
//	/**
//	 * @param args the command line arguments
//	 */
//	public static void main(String args[]) {
//		java.awt.EventQueue.invokeLater(new Runnable() {
//			public void run() {
//				GridBagTest g = new GridBagTest();
//				g.setVisible(true);
//				g.tst();
//			}
//		});
//	}
//	
//	public void tst(){
//		
////		for(int i = 0; i < 20; i++){
////			pnlMain.add(getPanel(), "0," + String.valueOf(i));
////			pnlMain.revalidate();			
////		}
//		pnlMain.add(getPanel(), "0,0,L, C");
//		pnlMain.add(getPanel(), "0,1,L,C");
//		pnlMain.add(getPanel(), "1,1,R,B");
//		
//		
//	}
//	
//	public JPanel getPanel(){
//		JPanel pnl = new JPanel();
//		pnl.setLayout(new TableLayout(new double[]{0.5, 0.5}, new double[]{20}));
//		pnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
//		
//		JLabel lbl = new JLabel("dneeme");
//		pnl.add(lbl, "0,0,R,C");
//		
//		
//		JTextField fld = new JTextField(20);
//		pnl.add(fld, "1, 0");
//		
////		((TableLayout)pnl.getLayout
//		return pnl;
//	}
//
//	//GEN-BEGIN:variables
//	// Variables declaration - do not modify
//	private javax.swing.JPanel pnlMain;
//	// End of variables declaration//GEN-END:variables

}
