//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.20 at 11:04:04 AM BST 
//


package org.openehr.schemas.v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openehr.schemas.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Archetype_QNAME = new QName("http://schemas.openehr.org/v1", "archetype");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openehr.schemas.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PARTYSELF }
     * 
     */
    public PARTYSELF createPARTYSELF() {
        return new PARTYSELF();
    }

    /**
     * Create an instance of {@link FEEDERAUDIT }
     * 
     */
    public FEEDERAUDIT createFEEDERAUDIT() {
        return new FEEDERAUDIT();
    }

    /**
     * Create an instance of {@link NONTERMINALSTATE }
     * 
     */
    public NONTERMINALSTATE createNONTERMINALSTATE() {
        return new NONTERMINALSTATE();
    }

    /**
     * Create an instance of {@link CBOOLEAN }
     * 
     */
    public CBOOLEAN createCBOOLEAN() {
        return new CBOOLEAN();
    }

    /**
     * Create an instance of {@link IntervalOfInteger }
     * 
     */
    public IntervalOfInteger createIntervalOfInteger() {
        return new IntervalOfInteger();
    }

    /**
     * Create an instance of {@link CQUANTITYITEM }
     * 
     */
    public CQUANTITYITEM createCQUANTITYITEM() {
        return new CQUANTITYITEM();
    }

    /**
     * Create an instance of {@link DVTEXT }
     * 
     */
    public DVTEXT createDVTEXT() {
        return new DVTEXT();
    }

    /**
     * Create an instance of {@link CTIME }
     * 
     */
    public CTIME createCTIME() {
        return new CTIME();
    }

    /**
     * Create an instance of {@link DVCOUNT }
     * 
     */
    public DVCOUNT createDVCOUNT() {
        return new DVCOUNT();
    }

    /**
     * Create an instance of {@link HIEROBJECTID }
     * 
     */
    public HIEROBJECTID createHIEROBJECTID() {
        return new HIEROBJECTID();
    }

    /**
     * Create an instance of {@link OBJECTREF }
     * 
     */
    public OBJECTREF createOBJECTREF() {
        return new OBJECTREF();
    }

    /**
     * Create an instance of {@link DVDATE }
     * 
     */
    public DVDATE createDVDATE() {
        return new DVDATE();
    }

    /**
     * Create an instance of {@link CPRIMITIVEOBJECT }
     * 
     */
    public CPRIMITIVEOBJECT createCPRIMITIVEOBJECT() {
        return new CPRIMITIVEOBJECT();
    }

    /**
     * Create an instance of {@link PARTYRELATED }
     * 
     */
    public PARTYRELATED createPARTYRELATED() {
        return new PARTYRELATED();
    }

    /**
     * Create an instance of {@link DVGENERALTIMESPECIFICATION }
     * 
     */
    public DVGENERALTIMESPECIFICATION createDVGENERALTIMESPECIFICATION() {
        return new DVGENERALTIMESPECIFICATION();
    }

    /**
     * Create an instance of {@link DVQUANTITY }
     * 
     */
    public DVQUANTITY createDVQUANTITY() {
        return new DVQUANTITY();
    }

    /**
     * Create an instance of {@link PARTICIPATION }
     * 
     */
    public PARTICIPATION createPARTICIPATION() {
        return new PARTICIPATION();
    }

    /**
     * Create an instance of {@link ATTESTATION }
     * 
     */
    public ATTESTATION createATTESTATION() {
        return new ATTESTATION();
    }

    /**
     * Create an instance of {@link DVTIME }
     * 
     */
    public DVTIME createDVTIME() {
        return new DVTIME();
    }

    /**
     * Create an instance of {@link TERMBINDINGITEM }
     * 
     */
    public TERMBINDINGITEM createTERMBINDINGITEM() {
        return new TERMBINDINGITEM();
    }

    /**
     * Create an instance of {@link TRANSLATIONDETAILS }
     * 
     */
    public TRANSLATIONDETAILS createTRANSLATIONDETAILS() {
        return new TRANSLATIONDETAILS();
    }

    /**
     * Create an instance of {@link ASSERTIONVARIABLE }
     * 
     */
    public ASSERTIONVARIABLE createASSERTIONVARIABLE() {
        return new ASSERTIONVARIABLE();
    }

    /**
     * Create an instance of {@link ARCHETYPEID }
     * 
     */
    public ARCHETYPEID createARCHETYPEID() {
        return new ARCHETYPEID();
    }

    /**
     * Create an instance of {@link RESOURCEDESCRIPTIONITEM }
     * 
     */
    public RESOURCEDESCRIPTIONITEM createRESOURCEDESCRIPTIONITEM() {
        return new RESOURCEDESCRIPTIONITEM();
    }

    /**
     * Create an instance of {@link CDEFINEDOBJECT }
     * 
     */
    public CDEFINEDOBJECT createCDEFINEDOBJECT() {
        return new CDEFINEDOBJECT();
    }

    /**
     * Create an instance of {@link DVCODEDTEXT }
     * 
     */
    public DVCODEDTEXT createDVCODEDTEXT() {
        return new DVCODEDTEXT();
    }

    /**
     * Create an instance of {@link DVSTATE }
     * 
     */
    public DVSTATE createDVSTATE() {
        return new DVSTATE();
    }

    /**
     * Create an instance of {@link CDVSTATE }
     * 
     */
    public CDVSTATE createCDVSTATE() {
        return new CDVSTATE();
    }

    /**
     * Create an instance of {@link STATEMACHINE }
     * 
     */
    public STATEMACHINE createSTATEMACHINE() {
        return new STATEMACHINE();
    }

    /**
     * Create an instance of {@link RESOURCEDESCRIPTION }
     * 
     */
    public RESOURCEDESCRIPTION createRESOURCEDESCRIPTION() {
        return new RESOURCEDESCRIPTION();
    }

    /**
     * Create an instance of {@link CodeDefinitionSet }
     * 
     */
    public CodeDefinitionSet createCodeDefinitionSet() {
        return new CodeDefinitionSet();
    }

    /**
     * Create an instance of {@link DVMULTIMEDIA }
     * 
     */
    public DVMULTIMEDIA createDVMULTIMEDIA() {
        return new DVMULTIMEDIA();
    }

    /**
     * Create an instance of {@link DVORDINAL }
     * 
     */
    public DVORDINAL createDVORDINAL() {
        return new DVORDINAL();
    }

    /**
     * Create an instance of {@link PARTYIDENTIFIED }
     * 
     */
    public PARTYIDENTIFIED createPARTYIDENTIFIED() {
        return new PARTYIDENTIFIED();
    }

    /**
     * Create an instance of {@link PARTYREF }
     * 
     */
    public PARTYREF createPARTYREF() {
        return new PARTYREF();
    }

    /**
     * Create an instance of {@link UIDBASEDID }
     * 
     */
    public UIDBASEDID createUIDBASEDID() {
        return new UIDBASEDID();
    }

    /**
     * Create an instance of {@link CREAL }
     * 
     */
    public CREAL createCREAL() {
        return new CREAL();
    }

    /**
     * Create an instance of {@link ARCHETYPEONTOLOGY }
     * 
     */
    public ARCHETYPEONTOLOGY createARCHETYPEONTOLOGY() {
        return new ARCHETYPEONTOLOGY();
    }

    /**
     * Create an instance of {@link IntervalOfDate }
     * 
     */
    public IntervalOfDate createIntervalOfDate() {
        return new IntervalOfDate();
    }

    /**
     * Create an instance of {@link IntervalOfReal }
     * 
     */
    public IntervalOfReal createIntervalOfReal() {
        return new IntervalOfReal();
    }

    /**
     * Create an instance of {@link FEEDERAUDITDETAILS }
     * 
     */
    public FEEDERAUDITDETAILS createFEEDERAUDITDETAILS() {
        return new FEEDERAUDITDETAILS();
    }

    /**
     * Create an instance of {@link CDURATION }
     * 
     */
    public CDURATION createCDURATION() {
        return new CDURATION();
    }

    /**
     * Create an instance of {@link TEMPLATEID }
     * 
     */
    public TEMPLATEID createTEMPLATEID() {
        return new TEMPLATEID();
    }

    /**
     * Create an instance of {@link LOCATABLEREF }
     * 
     */
    public LOCATABLEREF createLOCATABLEREF() {
        return new LOCATABLEREF();
    }

    /**
     * Create an instance of {@link ARCHETYPESLOT }
     * 
     */
    public ARCHETYPESLOT createARCHETYPESLOT() {
        return new ARCHETYPESLOT();
    }

    /**
     * Create an instance of {@link DVURI }
     * 
     */
    public DVURI createDVURI() {
        return new DVURI();
    }

    /**
     * Create an instance of {@link CCOMPLEXOBJECT }
     * 
     */
    public CCOMPLEXOBJECT createCCOMPLEXOBJECT() {
        return new CCOMPLEXOBJECT();
    }

    /**
     * Create an instance of {@link IntervalOfDuration }
     * 
     */
    public IntervalOfDuration createIntervalOfDuration() {
        return new IntervalOfDuration();
    }

    /**
     * Create an instance of {@link GENERICID }
     * 
     */
    public GENERICID createGENERICID() {
        return new GENERICID();
    }

    /**
     * Create an instance of {@link CDATETIME }
     * 
     */
    public CDATETIME createCDATETIME() {
        return new CDATETIME();
    }

    /**
     * Create an instance of {@link DVDURATION }
     * 
     */
    public DVDURATION createDVDURATION() {
        return new DVDURATION();
    }

    /**
     * Create an instance of {@link TERMINALSTATE }
     * 
     */
    public TERMINALSTATE createTERMINALSTATE() {
        return new TERMINALSTATE();
    }

    /**
     * Create an instance of {@link TERMMAPPING }
     * 
     */
    public TERMMAPPING createTERMMAPPING() {
        return new TERMMAPPING();
    }

    /**
     * Create an instance of {@link OBJECTVERSIONID }
     * 
     */
    public OBJECTVERSIONID createOBJECTVERSIONID() {
        return new OBJECTVERSIONID();
    }

    /**
     * Create an instance of {@link ARCHETYPEINTERNALREF }
     * 
     */
    public ARCHETYPEINTERNALREF createARCHETYPEINTERNALREF() {
        return new ARCHETYPEINTERNALREF();
    }

    /**
     * Create an instance of {@link DVPARAGRAPH }
     * 
     */
    public DVPARAGRAPH createDVPARAGRAPH() {
        return new DVPARAGRAPH();
    }

    /**
     * Create an instance of {@link AUTHOREDRESOURCE }
     * 
     */
    public AUTHOREDRESOURCE createAUTHOREDRESOURCE() {
        return new AUTHOREDRESOURCE();
    }

    /**
     * Create an instance of {@link DVIDENTIFIER }
     * 
     */
    public DVIDENTIFIER createDVIDENTIFIER() {
        return new DVIDENTIFIER();
    }

    /**
     * Create an instance of {@link StringDictionaryItem }
     * 
     */
    public StringDictionaryItem createStringDictionaryItem() {
        return new StringDictionaryItem();
    }

    /**
     * Create an instance of {@link AUDITDETAILS }
     * 
     */
    public AUDITDETAILS createAUDITDETAILS() {
        return new AUDITDETAILS();
    }

    /**
     * Create an instance of {@link CSTRING }
     * 
     */
    public CSTRING createCSTRING() {
        return new CSTRING();
    }

    /**
     * Create an instance of {@link ARCHETYPE }
     * 
     */
    public ARCHETYPE createARCHETYPE() {
        return new ARCHETYPE();
    }

    /**
     * Create an instance of {@link ACCESSGROUPREF }
     * 
     */
    public ACCESSGROUPREF createACCESSGROUPREF() {
        return new ACCESSGROUPREF();
    }

    /**
     * Create an instance of {@link EXPRUNARYOPERATOR }
     * 
     */
    public EXPRUNARYOPERATOR createEXPRUNARYOPERATOR() {
        return new EXPRUNARYOPERATOR();
    }

    /**
     * Create an instance of {@link EXPRLEAF }
     * 
     */
    public EXPRLEAF createEXPRLEAF() {
        return new EXPRLEAF();
    }

    /**
     * Create an instance of {@link ARCHETYPETERM }
     * 
     */
    public ARCHETYPETERM createARCHETYPETERM() {
        return new ARCHETYPETERM();
    }

    /**
     * Create an instance of {@link CDVQUANTITY }
     * 
     */
    public CDVQUANTITY createCDVQUANTITY() {
        return new CDVQUANTITY();
    }

    /**
     * Create an instance of {@link ASSERTION }
     * 
     */
    public ASSERTION createASSERTION() {
        return new ASSERTION();
    }

    /**
     * Create an instance of {@link TERMINOLOGYID }
     * 
     */
    public TERMINOLOGYID createTERMINOLOGYID() {
        return new TERMINOLOGYID();
    }

    /**
     * Create an instance of {@link IntervalOfDateTime }
     * 
     */
    public IntervalOfDateTime createIntervalOfDateTime() {
        return new IntervalOfDateTime();
    }

    /**
     * Create an instance of {@link REVISIONHISTORY }
     * 
     */
    public REVISIONHISTORY createREVISIONHISTORY() {
        return new REVISIONHISTORY();
    }

    /**
     * Create an instance of {@link DVPROPORTION }
     * 
     */
    public DVPROPORTION createDVPROPORTION() {
        return new DVPROPORTION();
    }

    /**
     * Create an instance of {@link CCODEPHRASE }
     * 
     */
    public CCODEPHRASE createCCODEPHRASE() {
        return new CCODEPHRASE();
    }

    /**
     * Create an instance of {@link CSINGLEATTRIBUTE }
     * 
     */
    public CSINGLEATTRIBUTE createCSINGLEATTRIBUTE() {
        return new CSINGLEATTRIBUTE();
    }

    /**
     * Create an instance of {@link DVDATETIME }
     * 
     */
    public DVDATETIME createDVDATETIME() {
        return new DVDATETIME();
    }

    /**
     * Create an instance of {@link DVPERIODICTIMESPECIFICATION }
     * 
     */
    public DVPERIODICTIMESPECIFICATION createDVPERIODICTIMESPECIFICATION() {
        return new DVPERIODICTIMESPECIFICATION();
    }

    /**
     * Create an instance of {@link REVISIONHISTORYITEM }
     * 
     */
    public REVISIONHISTORYITEM createREVISIONHISTORYITEM() {
        return new REVISIONHISTORYITEM();
    }

    /**
     * Create an instance of {@link TRANSITION }
     * 
     */
    public TRANSITION createTRANSITION() {
        return new TRANSITION();
    }

    /**
     * Create an instance of {@link CARDINALITY }
     * 
     */
    public CARDINALITY createCARDINALITY() {
        return new CARDINALITY();
    }

    /**
     * Create an instance of {@link CDATE }
     * 
     */
    public CDATE createCDATE() {
        return new CDATE();
    }

    /**
     * Create an instance of {@link EXPRBINARYOPERATOR }
     * 
     */
    public EXPRBINARYOPERATOR createEXPRBINARYOPERATOR() {
        return new EXPRBINARYOPERATOR();
    }

    /**
     * Create an instance of {@link ConstraintBindingSet }
     * 
     */
    public ConstraintBindingSet createConstraintBindingSet() {
        return new ConstraintBindingSet();
    }

    /**
     * Create an instance of {@link CDVORDINAL }
     * 
     */
    public CDVORDINAL createCDVORDINAL() {
        return new CDVORDINAL();
    }

    /**
     * Create an instance of {@link DVEHRURI }
     * 
     */
    public DVEHRURI createDVEHRURI() {
        return new DVEHRURI();
    }

    /**
     * Create an instance of {@link REFERENCERANGE }
     * 
     */
    public REFERENCERANGE createREFERENCERANGE() {
        return new REFERENCERANGE();
    }

    /**
     * Create an instance of {@link DVINTERVAL }
     * 
     */
    public DVINTERVAL createDVINTERVAL() {
        return new DVINTERVAL();
    }

    /**
     * Create an instance of {@link DVPARSABLE }
     * 
     */
    public DVPARSABLE createDVPARSABLE() {
        return new DVPARSABLE();
    }

    /**
     * Create an instance of {@link DVBOOLEAN }
     * 
     */
    public DVBOOLEAN createDVBOOLEAN() {
        return new DVBOOLEAN();
    }

    /**
     * Create an instance of {@link DVAMOUNT }
     * 
     */
    public DVAMOUNT createDVAMOUNT() {
        return new DVAMOUNT();
    }

    /**
     * Create an instance of {@link CONSTRAINTBINDINGITEM }
     * 
     */
    public CONSTRAINTBINDINGITEM createCONSTRAINTBINDINGITEM() {
        return new CONSTRAINTBINDINGITEM();
    }

    /**
     * Create an instance of {@link DVTEMPORAL }
     * 
     */
    public DVTEMPORAL createDVTEMPORAL() {
        return new DVTEMPORAL();
    }

    /**
     * Create an instance of {@link IntervalOfTime }
     * 
     */
    public IntervalOfTime createIntervalOfTime() {
        return new IntervalOfTime();
    }

    /**
     * Create an instance of {@link CONSTRAINTREF }
     * 
     */
    public CONSTRAINTREF createCONSTRAINTREF() {
        return new CONSTRAINTREF();
    }

    /**
     * Create an instance of {@link TermBindingSet }
     * 
     */
    public TermBindingSet createTermBindingSet() {
        return new TermBindingSet();
    }

    /**
     * Create an instance of {@link CODEPHRASE }
     * 
     */
    public CODEPHRASE createCODEPHRASE() {
        return new CODEPHRASE();
    }

    /**
     * Create an instance of {@link CINTEGER }
     * 
     */
    public CINTEGER createCINTEGER() {
        return new CINTEGER();
    }

    /**
     * Create an instance of {@link CMULTIPLEATTRIBUTE }
     * 
     */
    public CMULTIPLEATTRIBUTE createCMULTIPLEATTRIBUTE() {
        return new CMULTIPLEATTRIBUTE();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ARCHETYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.openehr.org/v1", name = "archetype")
    public JAXBElement<ARCHETYPE> createArchetype(ARCHETYPE value) {
        return new JAXBElement<ARCHETYPE>(_Archetype_QNAME, ARCHETYPE.class, null, value);
    }

}
