//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.12 at 12:10:04 PM BST 
//


package org.openehr.schemas.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ARCHETYPE_ONTOLOGY complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ARCHETYPE_ONTOLOGY">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="term_definitions" type="{http://schemas.openehr.org/v1}CodeDefinitionSet" maxOccurs="unbounded"/>
 *         &lt;element name="constraint_definitions" type="{http://schemas.openehr.org/v1}CodeDefinitionSet" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="term_bindings" type="{http://schemas.openehr.org/v1}TermBindingSet" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="constraint_bindings" type="{http://schemas.openehr.org/v1}ConstraintBindingSet" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ARCHETYPE_ONTOLOGY", propOrder = {
    "termDefinitions",
    "constraintDefinitions",
    "termBindings",
    "constraintBindings"
})
public class ARCHETYPEONTOLOGY {

    @XmlElement(name = "term_definitions", required = true)
    protected List<CodeDefinitionSet> termDefinitions;
    @XmlElement(name = "constraint_definitions")
    protected List<CodeDefinitionSet> constraintDefinitions;
    @XmlElement(name = "term_bindings")
    protected List<TermBindingSet> termBindings;
    @XmlElement(name = "constraint_bindings")
    protected List<ConstraintBindingSet> constraintBindings;

    /**
     * Gets the value of the termDefinitions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the termDefinitions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTermDefinitions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeDefinitionSet }
     * 
     * 
     */
    public List<CodeDefinitionSet> getTermDefinitions() {
        if (termDefinitions == null) {
            termDefinitions = new ArrayList<CodeDefinitionSet>();
        }
        return this.termDefinitions;
    }

    /**
     * Gets the value of the constraintDefinitions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the constraintDefinitions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConstraintDefinitions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeDefinitionSet }
     * 
     * 
     */
    public List<CodeDefinitionSet> getConstraintDefinitions() {
        if (constraintDefinitions == null) {
            constraintDefinitions = new ArrayList<CodeDefinitionSet>();
        }
        return this.constraintDefinitions;
    }

    /**
     * Gets the value of the termBindings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the termBindings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTermBindings().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TermBindingSet }
     * 
     * 
     */
    public List<TermBindingSet> getTermBindings() {
        if (termBindings == null) {
            termBindings = new ArrayList<TermBindingSet>();
        }
        return this.termBindings;
    }

    /**
     * Gets the value of the constraintBindings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the constraintBindings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConstraintBindings().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConstraintBindingSet }
     * 
     * 
     */
    public List<ConstraintBindingSet> getConstraintBindings() {
        if (constraintBindings == null) {
            constraintBindings = new ArrayList<ConstraintBindingSet>();
        }
        return this.constraintBindings;
    }

}
