/*******************************************************************************
 * Copyright 2012 Sevket Seref Arikan, David Ingram
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from aom.proto

package uk.ac.ucl.bosphorus.protostuff;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class CATTRIBUTEALTERNATIVES implements Externalizable, Message<CATTRIBUTEALTERNATIVES>
{

    public static Schema<CATTRIBUTEALTERNATIVES> getSchema()
    {
        return SCHEMA;
    }

    public static CATTRIBUTEALTERNATIVES getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final CATTRIBUTEALTERNATIVES DEFAULT_INSTANCE = new CATTRIBUTEALTERNATIVES();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    CSINGLEATTRIBUTE csingleattributefield;
    CMULTIPLEATTRIBUTE cmultipleattributefield;

    public CATTRIBUTEALTERNATIVES()
    {
        
    }

    // getters and setters

    // csingleattributefield

    public CSINGLEATTRIBUTE getCsingleattributefield()
    {
        return csingleattributefield;
    }

    public void setCsingleattributefield(CSINGLEATTRIBUTE csingleattributefield)
    {
        this.csingleattributefield = csingleattributefield;
    }

    // cmultipleattributefield

    public CMULTIPLEATTRIBUTE getCmultipleattributefield()
    {
        return cmultipleattributefield;
    }

    public void setCmultipleattributefield(CMULTIPLEATTRIBUTE cmultipleattributefield)
    {
        this.cmultipleattributefield = cmultipleattributefield;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<CATTRIBUTEALTERNATIVES> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<CATTRIBUTEALTERNATIVES> SCHEMA = new Schema<CATTRIBUTEALTERNATIVES>()
    {
        // schema methods

        public CATTRIBUTEALTERNATIVES newMessage()
        {
            return new CATTRIBUTEALTERNATIVES();
        }

        public Class<CATTRIBUTEALTERNATIVES> typeClass()
        {
            return CATTRIBUTEALTERNATIVES.class;
        }

        public String messageName()
        {
            return CATTRIBUTEALTERNATIVES.class.getSimpleName();
        }

        public String messageFullName()
        {
            return CATTRIBUTEALTERNATIVES.class.getName();
        }

        public boolean isInitialized(CATTRIBUTEALTERNATIVES message)
        {
            return true;
        }

        public void mergeFrom(Input input, CATTRIBUTEALTERNATIVES message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        message.csingleattributefield = input.mergeObject(message.csingleattributefield, CSINGLEATTRIBUTE.getSchema());
                        break;

                    case 2:
                        message.cmultipleattributefield = input.mergeObject(message.cmultipleattributefield, CMULTIPLEATTRIBUTE.getSchema());
                        break;

                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, CATTRIBUTEALTERNATIVES message) throws IOException
        {
            if(message.csingleattributefield != null)
                 output.writeObject(1, message.csingleattributefield, CSINGLEATTRIBUTE.getSchema(), false);


            if(message.cmultipleattributefield != null)
                 output.writeObject(2, message.cmultipleattributefield, CMULTIPLEATTRIBUTE.getSchema(), false);

        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "csingleattributefield";
                case 2: return "cmultipleattributefield";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("csingleattributefield", 1);
            fieldMap.put("cmultipleattributefield", 2);
        }
    };
    
}
