/*******************************************************************************
 * Copyright 2012 Sevket Seref Arikan, David Ingram
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from aom.proto

package uk.ac.ucl.bosphorus.protostuff;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class COBJECTALTERNATIVES implements Externalizable, Message<COBJECTALTERNATIVES>
{

    public static Schema<COBJECTALTERNATIVES> getSchema()
    {
        return SCHEMA;
    }

    public static COBJECTALTERNATIVES getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final COBJECTALTERNATIVES DEFAULT_INSTANCE = new COBJECTALTERNATIVES();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    CONSTRAINTREF constraintreffield;
    ARCHETYPESLOT archetypeslotfield;
    ARCHETYPEINTERNALREF archetypeinternalreffield;
    CDOMAINTYPE cdomaintypefield;
    CPRIMITIVEOBJECT cprimitiveobjectfield;
    CDEFINEDOBJECT cdefinedobjectfield;
    CCOMPLEXOBJECT ccomplexobjectfield;

    public COBJECTALTERNATIVES()
    {
        
    }

    // getters and setters

    // constraintreffield

    public CONSTRAINTREF getConstraintreffield()
    {
        return constraintreffield;
    }

    public void setConstraintreffield(CONSTRAINTREF constraintreffield)
    {
        this.constraintreffield = constraintreffield;
    }

    // archetypeslotfield

    public ARCHETYPESLOT getArchetypeslotfield()
    {
        return archetypeslotfield;
    }

    public void setArchetypeslotfield(ARCHETYPESLOT archetypeslotfield)
    {
        this.archetypeslotfield = archetypeslotfield;
    }

    // archetypeinternalreffield

    public ARCHETYPEINTERNALREF getArchetypeinternalreffield()
    {
        return archetypeinternalreffield;
    }

    public void setArchetypeinternalreffield(ARCHETYPEINTERNALREF archetypeinternalreffield)
    {
        this.archetypeinternalreffield = archetypeinternalreffield;
    }

    // cdomaintypefield

    public CDOMAINTYPE getCdomaintypefield()
    {
        return cdomaintypefield;
    }

    public void setCdomaintypefield(CDOMAINTYPE cdomaintypefield)
    {
        this.cdomaintypefield = cdomaintypefield;
    }

    // cprimitiveobjectfield

    public CPRIMITIVEOBJECT getCprimitiveobjectfield()
    {
        return cprimitiveobjectfield;
    }

    public void setCprimitiveobjectfield(CPRIMITIVEOBJECT cprimitiveobjectfield)
    {
        this.cprimitiveobjectfield = cprimitiveobjectfield;
    }

    // cdefinedobjectfield

    public CDEFINEDOBJECT getCdefinedobjectfield()
    {
        return cdefinedobjectfield;
    }

    public void setCdefinedobjectfield(CDEFINEDOBJECT cdefinedobjectfield)
    {
        this.cdefinedobjectfield = cdefinedobjectfield;
    }

    // ccomplexobjectfield

    public CCOMPLEXOBJECT getCcomplexobjectfield()
    {
        return ccomplexobjectfield;
    }

    public void setCcomplexobjectfield(CCOMPLEXOBJECT ccomplexobjectfield)
    {
        this.ccomplexobjectfield = ccomplexobjectfield;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<COBJECTALTERNATIVES> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<COBJECTALTERNATIVES> SCHEMA = new Schema<COBJECTALTERNATIVES>()
    {
        // schema methods

        public COBJECTALTERNATIVES newMessage()
        {
            return new COBJECTALTERNATIVES();
        }

        public Class<COBJECTALTERNATIVES> typeClass()
        {
            return COBJECTALTERNATIVES.class;
        }

        public String messageName()
        {
            return COBJECTALTERNATIVES.class.getSimpleName();
        }

        public String messageFullName()
        {
            return COBJECTALTERNATIVES.class.getName();
        }

        public boolean isInitialized(COBJECTALTERNATIVES message)
        {
            return true;
        }

        public void mergeFrom(Input input, COBJECTALTERNATIVES message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        message.constraintreffield = input.mergeObject(message.constraintreffield, CONSTRAINTREF.getSchema());
                        break;

                    case 2:
                        message.archetypeslotfield = input.mergeObject(message.archetypeslotfield, ARCHETYPESLOT.getSchema());
                        break;

                    case 3:
                        message.archetypeinternalreffield = input.mergeObject(message.archetypeinternalreffield, ARCHETYPEINTERNALREF.getSchema());
                        break;

                    case 4:
                        message.cdomaintypefield = input.mergeObject(message.cdomaintypefield, CDOMAINTYPE.getSchema());
                        break;

                    case 5:
                        message.cprimitiveobjectfield = input.mergeObject(message.cprimitiveobjectfield, CPRIMITIVEOBJECT.getSchema());
                        break;

                    case 6:
                        message.cdefinedobjectfield = input.mergeObject(message.cdefinedobjectfield, CDEFINEDOBJECT.getSchema());
                        break;

                    case 7:
                        message.ccomplexobjectfield = input.mergeObject(message.ccomplexobjectfield, CCOMPLEXOBJECT.getSchema());
                        break;

                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, COBJECTALTERNATIVES message) throws IOException
        {
            if(message.constraintreffield != null)
                 output.writeObject(1, message.constraintreffield, CONSTRAINTREF.getSchema(), false);


            if(message.archetypeslotfield != null)
                 output.writeObject(2, message.archetypeslotfield, ARCHETYPESLOT.getSchema(), false);


            if(message.archetypeinternalreffield != null)
                 output.writeObject(3, message.archetypeinternalreffield, ARCHETYPEINTERNALREF.getSchema(), false);


            if(message.cdomaintypefield != null)
                 output.writeObject(4, message.cdomaintypefield, CDOMAINTYPE.getSchema(), false);


            if(message.cprimitiveobjectfield != null)
                 output.writeObject(5, message.cprimitiveobjectfield, CPRIMITIVEOBJECT.getSchema(), false);


            if(message.cdefinedobjectfield != null)
                 output.writeObject(6, message.cdefinedobjectfield, CDEFINEDOBJECT.getSchema(), false);


            if(message.ccomplexobjectfield != null)
                 output.writeObject(7, message.ccomplexobjectfield, CCOMPLEXOBJECT.getSchema(), false);

        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "constraintreffield";
                case 2: return "archetypeslotfield";
                case 3: return "archetypeinternalreffield";
                case 4: return "cdomaintypefield";
                case 5: return "cprimitiveobjectfield";
                case 6: return "cdefinedobjectfield";
                case 7: return "ccomplexobjectfield";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("constraintreffield", 1);
            fieldMap.put("archetypeslotfield", 2);
            fieldMap.put("archetypeinternalreffield", 3);
            fieldMap.put("cdomaintypefield", 4);
            fieldMap.put("cprimitiveobjectfield", 5);
            fieldMap.put("cdefinedobjectfield", 6);
            fieldMap.put("ccomplexobjectfield", 7);
        }
    };
    
}
