/*******************************************************************************
 * Copyright 2012 Sevket Seref Arikan, David Ingram
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from aom.proto

package uk.ac.ucl.bosphorus.protostuff;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class CodeDefinitionSet implements Externalizable, Message<CodeDefinitionSet>
{

    public static Schema<CodeDefinitionSet> getSchema()
    {
        return SCHEMA;
    }

    public static CodeDefinitionSet getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final CodeDefinitionSet DEFAULT_INSTANCE = new CodeDefinitionSet();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    List<ARCHETYPETERM> items;
    String language;

    public CodeDefinitionSet()
    {
        
    }

    // getters and setters

    // items

    public List<ARCHETYPETERM> getItemsList()
    {
        return items;
    }

    public void setItemsList(List<ARCHETYPETERM> items)
    {
        this.items = items;
    }

    // language

    public String getLanguage()
    {
        return language;
    }

    public void setLanguage(String language)
    {
        this.language = language;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<CodeDefinitionSet> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<CodeDefinitionSet> SCHEMA = new Schema<CodeDefinitionSet>()
    {
        // schema methods

        public CodeDefinitionSet newMessage()
        {
            return new CodeDefinitionSet();
        }

        public Class<CodeDefinitionSet> typeClass()
        {
            return CodeDefinitionSet.class;
        }

        public String messageName()
        {
            return CodeDefinitionSet.class.getSimpleName();
        }

        public String messageFullName()
        {
            return CodeDefinitionSet.class.getName();
        }

        public boolean isInitialized(CodeDefinitionSet message)
        {
            return true;
        }

        public void mergeFrom(Input input, CodeDefinitionSet message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        if(message.items == null)
                            message.items = new ArrayList<ARCHETYPETERM>();
                        message.items.add(input.mergeObject(null, ARCHETYPETERM.getSchema()));
                        break;

                    case 2:
                        message.language = input.readString();
                        break;
                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, CodeDefinitionSet message) throws IOException
        {
            if(message.items != null)
            {
                for(ARCHETYPETERM items : message.items)
                {
                    if(items != null)
                        output.writeObject(1, items, ARCHETYPETERM.getSchema(), true);
                }
            }


            if(message.language != null)
                output.writeString(2, message.language, false);
        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "items";
                case 2: return "language";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("items", 1);
            fieldMap.put("language", 2);
        }
    };
    
}
