/*******************************************************************************
 * Copyright 2012 Sevket Seref Arikan, David Ingram
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from aom.proto

package uk.ac.ucl.bosphorus.protostuff;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public final class CPRIMITIVEOBJECT implements Externalizable, Message<CPRIMITIVEOBJECT>
{

    public static Schema<CPRIMITIVEOBJECT> getSchema()
    {
        return SCHEMA;
    }

    public static CPRIMITIVEOBJECT getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final CPRIMITIVEOBJECT DEFAULT_INSTANCE = new CPRIMITIVEOBJECT();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    CPRIMITIVEALTERNATIVES item;
    String rmtypename;
    IntervalOfInteger occurrences;
    String nodeid;

    public CPRIMITIVEOBJECT()
    {
        
    }

    public CPRIMITIVEOBJECT(
        String rmtypename,
        IntervalOfInteger occurrences,
        String nodeid
    )
    {
        this.rmtypename = rmtypename;
        this.occurrences = occurrences;
        this.nodeid = nodeid;
    }

    // getters and setters

    // item

    public CPRIMITIVEALTERNATIVES getItem()
    {
        return item;
    }

    public void setItem(CPRIMITIVEALTERNATIVES item)
    {
        this.item = item;
    }

    // rmtypename

    public String getRmtypename()
    {
        return rmtypename;
    }

    public void setRmtypename(String rmtypename)
    {
        this.rmtypename = rmtypename;
    }

    // occurrences

    public IntervalOfInteger getOccurrences()
    {
        return occurrences;
    }

    public void setOccurrences(IntervalOfInteger occurrences)
    {
        this.occurrences = occurrences;
    }

    // nodeid

    public String getNodeid()
    {
        return nodeid;
    }

    public void setNodeid(String nodeid)
    {
        this.nodeid = nodeid;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<CPRIMITIVEOBJECT> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<CPRIMITIVEOBJECT> SCHEMA = new Schema<CPRIMITIVEOBJECT>()
    {
        // schema methods

        public CPRIMITIVEOBJECT newMessage()
        {
            return new CPRIMITIVEOBJECT();
        }

        public Class<CPRIMITIVEOBJECT> typeClass()
        {
            return CPRIMITIVEOBJECT.class;
        }

        public String messageName()
        {
            return CPRIMITIVEOBJECT.class.getSimpleName();
        }

        public String messageFullName()
        {
            return CPRIMITIVEOBJECT.class.getName();
        }

        public boolean isInitialized(CPRIMITIVEOBJECT message)
        {
            return 
                message.rmtypename != null 
                && message.occurrences != null 
                && message.nodeid != null;
        }

        public void mergeFrom(Input input, CPRIMITIVEOBJECT message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        message.item = input.mergeObject(message.item, CPRIMITIVEALTERNATIVES.getSchema());
                        break;

                    case 2:
                        message.rmtypename = input.readString();
                        break;
                    case 3:
                        message.occurrences = input.mergeObject(message.occurrences, IntervalOfInteger.getSchema());
                        break;

                    case 4:
                        message.nodeid = input.readString();
                        break;
                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, CPRIMITIVEOBJECT message) throws IOException
        {
            if(message.item != null)
                 output.writeObject(1, message.item, CPRIMITIVEALTERNATIVES.getSchema(), false);


            if(message.rmtypename == null)
                throw new UninitializedMessageException(message);
            output.writeString(2, message.rmtypename, false);

            if(message.occurrences == null)
                throw new UninitializedMessageException(message);
            output.writeObject(3, message.occurrences, IntervalOfInteger.getSchema(), false);


            if(message.nodeid == null)
                throw new UninitializedMessageException(message);
            output.writeString(4, message.nodeid, false);
        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "item";
                case 2: return "rmtypename";
                case 3: return "occurrences";
                case 4: return "nodeid";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("item", 1);
            fieldMap.put("rmtypename", 2);
            fieldMap.put("occurrences", 3);
            fieldMap.put("nodeid", 4);
        }
    };
    
}
