/*******************************************************************************
 * Copyright 2012 Sevket Seref Arikan, David Ingram
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from aom.proto

package uk.ac.ucl.bosphorus.protostuff;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class DVENCAPSULATEDALTERNATIVES implements Externalizable, Message<DVENCAPSULATEDALTERNATIVES>
{

    public static Schema<DVENCAPSULATEDALTERNATIVES> getSchema()
    {
        return SCHEMA;
    }

    public static DVENCAPSULATEDALTERNATIVES getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final DVENCAPSULATEDALTERNATIVES DEFAULT_INSTANCE = new DVENCAPSULATEDALTERNATIVES();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    DVMULTIMEDIA dvmultimediafield;
    DVPARSABLE dvparsablefield;

    public DVENCAPSULATEDALTERNATIVES()
    {
        
    }

    // getters and setters

    // dvmultimediafield

    public DVMULTIMEDIA getDvmultimediafield()
    {
        return dvmultimediafield;
    }

    public void setDvmultimediafield(DVMULTIMEDIA dvmultimediafield)
    {
        this.dvmultimediafield = dvmultimediafield;
    }

    // dvparsablefield

    public DVPARSABLE getDvparsablefield()
    {
        return dvparsablefield;
    }

    public void setDvparsablefield(DVPARSABLE dvparsablefield)
    {
        this.dvparsablefield = dvparsablefield;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<DVENCAPSULATEDALTERNATIVES> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<DVENCAPSULATEDALTERNATIVES> SCHEMA = new Schema<DVENCAPSULATEDALTERNATIVES>()
    {
        // schema methods

        public DVENCAPSULATEDALTERNATIVES newMessage()
        {
            return new DVENCAPSULATEDALTERNATIVES();
        }

        public Class<DVENCAPSULATEDALTERNATIVES> typeClass()
        {
            return DVENCAPSULATEDALTERNATIVES.class;
        }

        public String messageName()
        {
            return DVENCAPSULATEDALTERNATIVES.class.getSimpleName();
        }

        public String messageFullName()
        {
            return DVENCAPSULATEDALTERNATIVES.class.getName();
        }

        public boolean isInitialized(DVENCAPSULATEDALTERNATIVES message)
        {
            return true;
        }

        public void mergeFrom(Input input, DVENCAPSULATEDALTERNATIVES message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        message.dvmultimediafield = input.mergeObject(message.dvmultimediafield, DVMULTIMEDIA.getSchema());
                        break;

                    case 2:
                        message.dvparsablefield = input.mergeObject(message.dvparsablefield, DVPARSABLE.getSchema());
                        break;

                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, DVENCAPSULATEDALTERNATIVES message) throws IOException
        {
            if(message.dvmultimediafield != null)
                 output.writeObject(1, message.dvmultimediafield, DVMULTIMEDIA.getSchema(), false);


            if(message.dvparsablefield != null)
                 output.writeObject(2, message.dvparsablefield, DVPARSABLE.getSchema(), false);

        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "dvmultimediafield";
                case 2: return "dvparsablefield";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("dvmultimediafield", 1);
            fieldMap.put("dvparsablefield", 2);
        }
    };
    
}
