/*******************************************************************************
 * Copyright 2012 Sevket Seref Arikan, David Ingram
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from aom.proto

package uk.ac.ucl.bosphorus.protostuff;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public final class EXPRLEAF implements Externalizable, Message<EXPRLEAF>
{

    public static Schema<EXPRLEAF> getSchema()
    {
        return SCHEMA;
    }

    public static EXPRLEAF getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final EXPRLEAF DEFAULT_INSTANCE = new EXPRLEAF();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    String item;
    String referencetype;
    String type;

    public EXPRLEAF()
    {
        
    }

    public EXPRLEAF(
        String item,
        String referencetype,
        String type
    )
    {
        this.item = item;
        this.referencetype = referencetype;
        this.type = type;
    }

    // getters and setters

    // item

    public String getItem()
    {
        return item;
    }

    public void setItem(String item)
    {
        this.item = item;
    }

    // referencetype

    public String getReferencetype()
    {
        return referencetype;
    }

    public void setReferencetype(String referencetype)
    {
        this.referencetype = referencetype;
    }

    // type

    public String getType()
    {
        return type;
    }

    public void setType(String type)
    {
        this.type = type;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<EXPRLEAF> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<EXPRLEAF> SCHEMA = new Schema<EXPRLEAF>()
    {
        // schema methods

        public EXPRLEAF newMessage()
        {
            return new EXPRLEAF();
        }

        public Class<EXPRLEAF> typeClass()
        {
            return EXPRLEAF.class;
        }

        public String messageName()
        {
            return EXPRLEAF.class.getSimpleName();
        }

        public String messageFullName()
        {
            return EXPRLEAF.class.getName();
        }

        public boolean isInitialized(EXPRLEAF message)
        {
            return 
                message.item != null 
                && message.referencetype != null 
                && message.type != null;
        }

        public void mergeFrom(Input input, EXPRLEAF message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        message.item = input.readString();
                        break;
                    case 2:
                        message.referencetype = input.readString();
                        break;
                    case 3:
                        message.type = input.readString();
                        break;
                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, EXPRLEAF message) throws IOException
        {
            if(message.item == null)
                throw new UninitializedMessageException(message);
            output.writeString(1, message.item, false);

            if(message.referencetype == null)
                throw new UninitializedMessageException(message);
            output.writeString(2, message.referencetype, false);

            if(message.type == null)
                throw new UninitializedMessageException(message);
            output.writeString(3, message.type, false);
        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "item";
                case 2: return "referencetype";
                case 3: return "type";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("item", 1);
            fieldMap.put("referencetype", 2);
            fieldMap.put("type", 3);
        }
    };
    
}
