/*******************************************************************************
 * Copyright 2012 Sevket Seref Arikan, David Ingram
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from aom.proto

package uk.ac.ucl.bosphorus.protostuff;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class EXPROPERATORALTERNATIVES implements Externalizable, Message<EXPROPERATORALTERNATIVES>
{

    public static Schema<EXPROPERATORALTERNATIVES> getSchema()
    {
        return SCHEMA;
    }

    public static EXPROPERATORALTERNATIVES getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final EXPROPERATORALTERNATIVES DEFAULT_INSTANCE = new EXPROPERATORALTERNATIVES();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    EXPRBINARYOPERATOR exprbinaryoperatorfield;
    EXPRUNARYOPERATOR exprunaryoperatorfield;

    public EXPROPERATORALTERNATIVES()
    {
        
    }

    // getters and setters

    // exprbinaryoperatorfield

    public EXPRBINARYOPERATOR getExprbinaryoperatorfield()
    {
        return exprbinaryoperatorfield;
    }

    public void setExprbinaryoperatorfield(EXPRBINARYOPERATOR exprbinaryoperatorfield)
    {
        this.exprbinaryoperatorfield = exprbinaryoperatorfield;
    }

    // exprunaryoperatorfield

    public EXPRUNARYOPERATOR getExprunaryoperatorfield()
    {
        return exprunaryoperatorfield;
    }

    public void setExprunaryoperatorfield(EXPRUNARYOPERATOR exprunaryoperatorfield)
    {
        this.exprunaryoperatorfield = exprunaryoperatorfield;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<EXPROPERATORALTERNATIVES> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<EXPROPERATORALTERNATIVES> SCHEMA = new Schema<EXPROPERATORALTERNATIVES>()
    {
        // schema methods

        public EXPROPERATORALTERNATIVES newMessage()
        {
            return new EXPROPERATORALTERNATIVES();
        }

        public Class<EXPROPERATORALTERNATIVES> typeClass()
        {
            return EXPROPERATORALTERNATIVES.class;
        }

        public String messageName()
        {
            return EXPROPERATORALTERNATIVES.class.getSimpleName();
        }

        public String messageFullName()
        {
            return EXPROPERATORALTERNATIVES.class.getName();
        }

        public boolean isInitialized(EXPROPERATORALTERNATIVES message)
        {
            return true;
        }

        public void mergeFrom(Input input, EXPROPERATORALTERNATIVES message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        message.exprbinaryoperatorfield = input.mergeObject(message.exprbinaryoperatorfield, EXPRBINARYOPERATOR.getSchema());
                        break;

                    case 2:
                        message.exprunaryoperatorfield = input.mergeObject(message.exprunaryoperatorfield, EXPRUNARYOPERATOR.getSchema());
                        break;

                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, EXPROPERATORALTERNATIVES message) throws IOException
        {
            if(message.exprbinaryoperatorfield != null)
                 output.writeObject(1, message.exprbinaryoperatorfield, EXPRBINARYOPERATOR.getSchema(), false);


            if(message.exprunaryoperatorfield != null)
                 output.writeObject(2, message.exprunaryoperatorfield, EXPRUNARYOPERATOR.getSchema(), false);

        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "exprbinaryoperatorfield";
                case 2: return "exprunaryoperatorfield";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("exprbinaryoperatorfield", 1);
            fieldMap.put("exprunaryoperatorfield", 2);
        }
    };
    
}
