/*******************************************************************************
 * Copyright 2012 Sevket Seref Arikan, David Ingram
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from aom.proto

package uk.ac.ucl.bosphorus.protostuff;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class PARTYPROXY implements Externalizable, Message<PARTYPROXY>
{

    public static Schema<PARTYPROXY> getSchema()
    {
        return SCHEMA;
    }

    public static PARTYPROXY getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final PARTYPROXY DEFAULT_INSTANCE = new PARTYPROXY();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    PARTYREF externalref;

    public PARTYPROXY()
    {
        
    }

    // getters and setters

    // externalref

    public PARTYREF getExternalref()
    {
        return externalref;
    }

    public void setExternalref(PARTYREF externalref)
    {
        this.externalref = externalref;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<PARTYPROXY> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<PARTYPROXY> SCHEMA = new Schema<PARTYPROXY>()
    {
        // schema methods

        public PARTYPROXY newMessage()
        {
            return new PARTYPROXY();
        }

        public Class<PARTYPROXY> typeClass()
        {
            return PARTYPROXY.class;
        }

        public String messageName()
        {
            return PARTYPROXY.class.getSimpleName();
        }

        public String messageFullName()
        {
            return PARTYPROXY.class.getName();
        }

        public boolean isInitialized(PARTYPROXY message)
        {
            return true;
        }

        public void mergeFrom(Input input, PARTYPROXY message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        message.externalref = input.mergeObject(message.externalref, PARTYREF.getSchema());
                        break;

                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, PARTYPROXY message) throws IOException
        {
            if(message.externalref != null)
                 output.writeObject(1, message.externalref, PARTYREF.getSchema(), false);

        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "externalref";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("externalref", 1);
        }
    };
    
}
