/*******************************************************************************
 * Copyright 2012 Sevket Seref Arikan, David Ingram
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from aom.proto

package uk.ac.ucl.bosphorus.protostuff;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class REVISIONHISTORY implements Externalizable, Message<REVISIONHISTORY>
{

    public static Schema<REVISIONHISTORY> getSchema()
    {
        return SCHEMA;
    }

    public static REVISIONHISTORY getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final REVISIONHISTORY DEFAULT_INSTANCE = new REVISIONHISTORY();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    List<REVISIONHISTORYITEM> items;

    public REVISIONHISTORY()
    {
        
    }

    // getters and setters

    // items

    public List<REVISIONHISTORYITEM> getItemsList()
    {
        return items;
    }

    public void setItemsList(List<REVISIONHISTORYITEM> items)
    {
        this.items = items;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<REVISIONHISTORY> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<REVISIONHISTORY> SCHEMA = new Schema<REVISIONHISTORY>()
    {
        // schema methods

        public REVISIONHISTORY newMessage()
        {
            return new REVISIONHISTORY();
        }

        public Class<REVISIONHISTORY> typeClass()
        {
            return REVISIONHISTORY.class;
        }

        public String messageName()
        {
            return REVISIONHISTORY.class.getSimpleName();
        }

        public String messageFullName()
        {
            return REVISIONHISTORY.class.getName();
        }

        public boolean isInitialized(REVISIONHISTORY message)
        {
            return true;
        }

        public void mergeFrom(Input input, REVISIONHISTORY message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        if(message.items == null)
                            message.items = new ArrayList<REVISIONHISTORYITEM>();
                        message.items.add(input.mergeObject(null, REVISIONHISTORYITEM.getSchema()));
                        break;

                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, REVISIONHISTORY message) throws IOException
        {
            if(message.items != null)
            {
                for(REVISIONHISTORYITEM items : message.items)
                {
                    if(items != null)
                        output.writeObject(1, items, REVISIONHISTORYITEM.getSchema(), true);
                }
            }

        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "items";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("items", 1);
        }
    };
    
}
