/*******************************************************************************
 * Copyright 2012 Sevket Seref Arikan, David Ingram
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from aom.proto

package uk.ac.ucl.bosphorus.protostuff;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class TermBindingSet implements Externalizable, Message<TermBindingSet>
{

    public static Schema<TermBindingSet> getSchema()
    {
        return SCHEMA;
    }

    public static TermBindingSet getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final TermBindingSet DEFAULT_INSTANCE = new TermBindingSet();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    List<TERMBINDINGITEM> items;
    String terminology;

    public TermBindingSet()
    {
        
    }

    // getters and setters

    // items

    public List<TERMBINDINGITEM> getItemsList()
    {
        return items;
    }

    public void setItemsList(List<TERMBINDINGITEM> items)
    {
        this.items = items;
    }

    // terminology

    public String getTerminology()
    {
        return terminology;
    }

    public void setTerminology(String terminology)
    {
        this.terminology = terminology;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<TermBindingSet> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<TermBindingSet> SCHEMA = new Schema<TermBindingSet>()
    {
        // schema methods

        public TermBindingSet newMessage()
        {
            return new TermBindingSet();
        }

        public Class<TermBindingSet> typeClass()
        {
            return TermBindingSet.class;
        }

        public String messageName()
        {
            return TermBindingSet.class.getSimpleName();
        }

        public String messageFullName()
        {
            return TermBindingSet.class.getName();
        }

        public boolean isInitialized(TermBindingSet message)
        {
            return true;
        }

        public void mergeFrom(Input input, TermBindingSet message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        if(message.items == null)
                            message.items = new ArrayList<TERMBINDINGITEM>();
                        message.items.add(input.mergeObject(null, TERMBINDINGITEM.getSchema()));
                        break;

                    case 2:
                        message.terminology = input.readString();
                        break;
                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, TermBindingSet message) throws IOException
        {
            if(message.items != null)
            {
                for(TERMBINDINGITEM items : message.items)
                {
                    if(items != null)
                        output.writeObject(1, items, TERMBINDINGITEM.getSchema(), true);
                }
            }


            if(message.terminology != null)
                output.writeString(2, message.terminology, false);
        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "items";
                case 2: return "terminology";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("items", 1);
            fieldMap.put("terminology", 2);
        }
    };
    
}
