// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from aom.proto

package bosphorus;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public final class ARCHETYPESLOT implements Externalizable, Message<ARCHETYPESLOT>, Schema<ARCHETYPESLOT>
{

    public static Schema<ARCHETYPESLOT> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static ARCHETYPESLOT getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final ARCHETYPESLOT DEFAULT_INSTANCE = new ARCHETYPESLOT();

    
    private List<ASSERTION> includes;
    private List<ASSERTION> excludes;
    private String rmtypename;
    private IntervalOfInteger occurrences;
    private String nodeid;

    public ARCHETYPESLOT()
    {
        
    }

    public ARCHETYPESLOT(
        String rmtypename,
        IntervalOfInteger occurrences,
        String nodeid
    )
    {
        this.rmtypename = rmtypename;
        this.occurrences = occurrences;
        this.nodeid = nodeid;
    }

    // getters and setters

    // includes

    public List<ASSERTION> getIncludesList()
    {
        return includes;
    }

    public void setIncludesList(List<ASSERTION> includes)
    {
        this.includes = includes;
    }

    // excludes

    public List<ASSERTION> getExcludesList()
    {
        return excludes;
    }

    public void setExcludesList(List<ASSERTION> excludes)
    {
        this.excludes = excludes;
    }

    // rmtypename

    public String getRmtypename()
    {
        return rmtypename;
    }

    public void setRmtypename(String rmtypename)
    {
        this.rmtypename = rmtypename;
    }

    // occurrences

    public IntervalOfInteger getOccurrences()
    {
        return occurrences;
    }

    public void setOccurrences(IntervalOfInteger occurrences)
    {
        this.occurrences = occurrences;
    }

    // nodeid

    public String getNodeid()
    {
        return nodeid;
    }

    public void setNodeid(String nodeid)
    {
        this.nodeid = nodeid;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<ARCHETYPESLOT> cachedSchema()
    {
        return this;
    }

    // schema methods

    public ARCHETYPESLOT newMessage()
    {
        return new ARCHETYPESLOT();
    }

    public Class<ARCHETYPESLOT> typeClass()
    {
        return ARCHETYPESLOT.class;
    }

    public String messageName()
    {
        return ARCHETYPESLOT.class.getSimpleName();
    }

    public String messageFullName()
    {
        return ARCHETYPESLOT.class.getName();
    }

    public boolean isInitialized(ARCHETYPESLOT message)
    {
        return 
            message.rmtypename != null 
            && message.occurrences != null 
            && message.nodeid != null;
    }

    public void mergeFrom(Input input, ARCHETYPESLOT message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 1:
                    if(message.includes == null)
                        message.includes = new ArrayList<ASSERTION>();
                    message.includes.add(input.mergeObject(null, ASSERTION.getSchema()));
                    break;

                case 2:
                    if(message.excludes == null)
                        message.excludes = new ArrayList<ASSERTION>();
                    message.excludes.add(input.mergeObject(null, ASSERTION.getSchema()));
                    break;

                case 3:
                    message.rmtypename = input.readString();
                    break;
                case 4:
                    message.occurrences = input.mergeObject(message.occurrences, IntervalOfInteger.getSchema());
                    break;

                case 5:
                    message.nodeid = input.readString();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, ARCHETYPESLOT message) throws IOException
    {
        if(message.includes != null)
        {
            for(ASSERTION includes : message.includes)
            {
                if(includes != null)
                    output.writeObject(1, includes, ASSERTION.getSchema(), true);
            }
        }


        if(message.excludes != null)
        {
            for(ASSERTION excludes : message.excludes)
            {
                if(excludes != null)
                    output.writeObject(2, excludes, ASSERTION.getSchema(), true);
            }
        }


        if(message.rmtypename == null)
            throw new UninitializedMessageException(message);
        output.writeString(3, message.rmtypename, false);

        if(message.occurrences == null)
            throw new UninitializedMessageException(message);
        output.writeObject(4, message.occurrences, IntervalOfInteger.getSchema(), false);


        if(message.nodeid == null)
            throw new UninitializedMessageException(message);
        output.writeString(5, message.nodeid, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
