// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from aom.proto

package bosphorus;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class DVTEMPORAL implements Externalizable, Message<DVTEMPORAL>, Schema<DVTEMPORAL>
{

    public static Schema<DVTEMPORAL> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static DVTEMPORAL getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final DVTEMPORAL DEFAULT_INSTANCE = new DVTEMPORAL();

    
    private DVDURATION accuracy;
    private DVINTERVAL normalrange;
    private List<REFERENCERANGE> otherreferenceranges;
    private CODEPHRASE normalstatus;
    private String magnitudestatus;

    public DVTEMPORAL()
    {
        
    }

    // getters and setters

    // accuracy

    public DVDURATION getAccuracy()
    {
        return accuracy;
    }

    public void setAccuracy(DVDURATION accuracy)
    {
        this.accuracy = accuracy;
    }

    // normalrange

    public DVINTERVAL getNormalrange()
    {
        return normalrange;
    }

    public void setNormalrange(DVINTERVAL normalrange)
    {
        this.normalrange = normalrange;
    }

    // otherreferenceranges

    public List<REFERENCERANGE> getOtherreferencerangesList()
    {
        return otherreferenceranges;
    }

    public void setOtherreferencerangesList(List<REFERENCERANGE> otherreferenceranges)
    {
        this.otherreferenceranges = otherreferenceranges;
    }

    // normalstatus

    public CODEPHRASE getNormalstatus()
    {
        return normalstatus;
    }

    public void setNormalstatus(CODEPHRASE normalstatus)
    {
        this.normalstatus = normalstatus;
    }

    // magnitudestatus

    public String getMagnitudestatus()
    {
        return magnitudestatus;
    }

    public void setMagnitudestatus(String magnitudestatus)
    {
        this.magnitudestatus = magnitudestatus;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<DVTEMPORAL> cachedSchema()
    {
        return this;
    }

    // schema methods

    public DVTEMPORAL newMessage()
    {
        return new DVTEMPORAL();
    }

    public Class<DVTEMPORAL> typeClass()
    {
        return DVTEMPORAL.class;
    }

    public String messageName()
    {
        return DVTEMPORAL.class.getSimpleName();
    }

    public String messageFullName()
    {
        return DVTEMPORAL.class.getName();
    }

    public boolean isInitialized(DVTEMPORAL message)
    {
        return true;
    }

    public void mergeFrom(Input input, DVTEMPORAL message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 1:
                    message.accuracy = input.mergeObject(message.accuracy, DVDURATION.getSchema());
                    break;

                case 2:
                    message.normalrange = input.mergeObject(message.normalrange, DVINTERVAL.getSchema());
                    break;

                case 3:
                    if(message.otherreferenceranges == null)
                        message.otherreferenceranges = new ArrayList<REFERENCERANGE>();
                    message.otherreferenceranges.add(input.mergeObject(null, REFERENCERANGE.getSchema()));
                    break;

                case 4:
                    message.normalstatus = input.mergeObject(message.normalstatus, CODEPHRASE.getSchema());
                    break;

                case 5:
                    message.magnitudestatus = input.readString();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, DVTEMPORAL message) throws IOException
    {
        if(message.accuracy != null)
             output.writeObject(1, message.accuracy, DVDURATION.getSchema(), false);


        if(message.normalrange != null)
             output.writeObject(2, message.normalrange, DVINTERVAL.getSchema(), false);


        if(message.otherreferenceranges != null)
        {
            for(REFERENCERANGE otherreferenceranges : message.otherreferenceranges)
            {
                if(otherreferenceranges != null)
                    output.writeObject(3, otherreferenceranges, REFERENCERANGE.getSchema(), true);
            }
        }


        if(message.normalstatus != null)
             output.writeObject(4, message.normalstatus, CODEPHRASE.getSchema(), false);


        if(message.magnitudestatus != null)
            output.writeString(5, message.magnitudestatus, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
