// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from aom.proto

package bosphorus;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class Interval implements Externalizable, Message<Interval>, Schema<Interval>
{

    public static Schema<Interval> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static Interval getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final Interval DEFAULT_INSTANCE = new Interval();

    
    private Boolean lowerincluded;
    private Boolean upperincluded;
    private Boolean lowerunbounded;
    private Boolean upperunbounded;

    public Interval()
    {
        
    }

    // getters and setters

    // lowerincluded

    public Boolean getLowerincluded()
    {
        return lowerincluded;
    }

    public void setLowerincluded(Boolean lowerincluded)
    {
        this.lowerincluded = lowerincluded;
    }

    // upperincluded

    public Boolean getUpperincluded()
    {
        return upperincluded;
    }

    public void setUpperincluded(Boolean upperincluded)
    {
        this.upperincluded = upperincluded;
    }

    // lowerunbounded

    public Boolean getLowerunbounded()
    {
        return lowerunbounded;
    }

    public void setLowerunbounded(Boolean lowerunbounded)
    {
        this.lowerunbounded = lowerunbounded;
    }

    // upperunbounded

    public Boolean getUpperunbounded()
    {
        return upperunbounded;
    }

    public void setUpperunbounded(Boolean upperunbounded)
    {
        this.upperunbounded = upperunbounded;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<Interval> cachedSchema()
    {
        return this;
    }

    // schema methods

    public Interval newMessage()
    {
        return new Interval();
    }

    public Class<Interval> typeClass()
    {
        return Interval.class;
    }

    public String messageName()
    {
        return Interval.class.getSimpleName();
    }

    public String messageFullName()
    {
        return Interval.class.getName();
    }

    public boolean isInitialized(Interval message)
    {
        return true;
    }

    public void mergeFrom(Input input, Interval message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 1:
                    message.lowerincluded = input.readBool();
                    break;
                case 2:
                    message.upperincluded = input.readBool();
                    break;
                case 3:
                    message.lowerunbounded = input.readBool();
                    break;
                case 4:
                    message.upperunbounded = input.readBool();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, Interval message) throws IOException
    {
        if(message.lowerincluded != null)
            output.writeBool(1, message.lowerincluded, false);

        if(message.upperincluded != null)
            output.writeBool(2, message.upperincluded, false);

        if(message.lowerunbounded != null)
            output.writeBool(3, message.lowerunbounded, false);

        if(message.upperunbounded != null)
            output.writeBool(4, message.upperunbounded, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
