// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from aom.proto

package bosphorus;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class PARTYIDENTIFIED implements Externalizable, Message<PARTYIDENTIFIED>, Schema<PARTYIDENTIFIED>
{

    public static Schema<PARTYIDENTIFIED> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static PARTYIDENTIFIED getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final PARTYIDENTIFIED DEFAULT_INSTANCE = new PARTYIDENTIFIED();

    
    private String name;
    private List<DVIDENTIFIER> identifiers;
    private PARTYREF externalref;

    public PARTYIDENTIFIED()
    {
        
    }

    // getters and setters

    // name

    public String getName()
    {
        return name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    // identifiers

    public List<DVIDENTIFIER> getIdentifiersList()
    {
        return identifiers;
    }

    public void setIdentifiersList(List<DVIDENTIFIER> identifiers)
    {
        this.identifiers = identifiers;
    }

    // externalref

    public PARTYREF getExternalref()
    {
        return externalref;
    }

    public void setExternalref(PARTYREF externalref)
    {
        this.externalref = externalref;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<PARTYIDENTIFIED> cachedSchema()
    {
        return this;
    }

    // schema methods

    public PARTYIDENTIFIED newMessage()
    {
        return new PARTYIDENTIFIED();
    }

    public Class<PARTYIDENTIFIED> typeClass()
    {
        return PARTYIDENTIFIED.class;
    }

    public String messageName()
    {
        return PARTYIDENTIFIED.class.getSimpleName();
    }

    public String messageFullName()
    {
        return PARTYIDENTIFIED.class.getName();
    }

    public boolean isInitialized(PARTYIDENTIFIED message)
    {
        return true;
    }

    public void mergeFrom(Input input, PARTYIDENTIFIED message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 1:
                    message.name = input.readString();
                    break;
                case 2:
                    if(message.identifiers == null)
                        message.identifiers = new ArrayList<DVIDENTIFIER>();
                    message.identifiers.add(input.mergeObject(null, DVIDENTIFIER.getSchema()));
                    break;

                case 3:
                    message.externalref = input.mergeObject(message.externalref, PARTYREF.getSchema());
                    break;

                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, PARTYIDENTIFIED message) throws IOException
    {
        if(message.name != null)
            output.writeString(1, message.name, false);

        if(message.identifiers != null)
        {
            for(DVIDENTIFIER identifiers : message.identifiers)
            {
                if(identifiers != null)
                    output.writeObject(2, identifiers, DVIDENTIFIER.getSchema(), true);
            }
        }


        if(message.externalref != null)
             output.writeObject(3, message.externalref, PARTYREF.getSchema(), false);

    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
