// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from aom.proto

package bosphorus;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class StringDictionaryItem implements Externalizable, Message<StringDictionaryItem>, Schema<StringDictionaryItem>
{

    public static Schema<StringDictionaryItem> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static StringDictionaryItem getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final StringDictionaryItem DEFAULT_INSTANCE = new StringDictionaryItem();

    
    private String value;
    private String id;

    public StringDictionaryItem()
    {
        
    }

    // getters and setters

    // value

    public String getValue()
    {
        return value;
    }

    public void setValue(String value)
    {
        this.value = value;
    }

    // id

    public String getId()
    {
        return id;
    }

    public void setId(String id)
    {
        this.id = id;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<StringDictionaryItem> cachedSchema()
    {
        return this;
    }

    // schema methods

    public StringDictionaryItem newMessage()
    {
        return new StringDictionaryItem();
    }

    public Class<StringDictionaryItem> typeClass()
    {
        return StringDictionaryItem.class;
    }

    public String messageName()
    {
        return StringDictionaryItem.class.getSimpleName();
    }

    public String messageFullName()
    {
        return StringDictionaryItem.class.getName();
    }

    public boolean isInitialized(StringDictionaryItem message)
    {
        return true;
    }

    public void mergeFrom(Input input, StringDictionaryItem message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 1:
                    message.value = input.readString();
                    break;
                case 2:
                    message.id = input.readString();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, StringDictionaryItem message) throws IOException
    {
        if(message.value != null)
            output.writeString(1, message.value, false);

        if(message.id != null)
            output.writeString(2, message.id, false);
    }

    public String getFieldName(int number)
    {
        return Integer.toString(number);
    }

    public int getFieldNumber(String name)
    {
        return Integer.parseInt(name);
    }
    
}
